### ISSUE TITLE
[bug] Domain is EPFL instead of INTRANET

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-si/ATARI#63]
The EPFL's AD domain is INTRANET

**Comment by Azecko** [comment]
As talked with [Victor](https://www.google.com/search?client=ubuntu-sn&channel=fs&q=Victor+Vesselinov+Garvalov), it seems like ATARI is doing the right job.
Some users have "EPFL" (ex. Martin Vetterli)
And some users have "INTRANET" (ex. Anne-Sarah Léorie Amblard (user in the screenshot))

![image](https://github.com/epfl-si/ATARI/assets/30987143/dbf3230d-545d-4324-98ff-ea3dc5b91f75)

So, I take the responsability to close this issue. But feel free to tell me if I'm wrong.

**Comment by ponsfrilus** [comment]
@lvenries any ideas why the domain might be `EPFL` instead of `INTRANET`?
