### ISSUE TITLE
[bug] can't find person 401102

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-si/ATARI#68]
While this person has an entry on people.epfl.ch it can't be found on ATARI.
Also see https://go.epfl.ch/INC0636612

**Comment by ponsfrilus** [comment]
1. OK with https://people.epfl.ch/401102
2. OK with https://api.epfl.ch/v1/accreds?persid=401102
3. FAILS with https://api.epfl.ch/v1/persons/401102 (return null)
4. FAILS with https://api.epfl.ch/v1/persons?query=401102 (return `{"count": 0,"persons": []}`)

**Comment by Azecko** [comment]
The problem was created because of a bad `JOIN` instead of a `LEFT JOIN` in api.epfl.ch
It is now fixed.
Closing this issue
