### ISSUE TITLE
[bug] Can authenticate with Chrome

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-si/ATARI#69]
This has to be investigated.

**Comment by Azecko** [comment]
Hey @domq !
ServiceDesk@EPFL really needs for ATARI to work with Chrome.
Can we check this together ASAP ?

**Comment by Azecko** [comment]
Thanks to @domq, problem has been fixed [here](https://github.com/epfl-si/satosa-tequila/commit/2c34d2fd09d17c3b513dc0ff8bb442ec1bce7193)
