### ISSUE TITLE
[feature] Add a link to camipro admin in TOOLS

### ISSUE THREAD

**Issue by fredl2020** [epfl-si/ATARI#95]
Is it possible to add a link to camipro admin https://mycamipro.epfl.ch/admin/?page=cmpcardhist 
This link is very useful for our SA to check some info when requesting 2fa, mfa

**Comment by Azecko** [comment]
Hey !
What is a `cmpcardhist` ? And where is that information findable ?

**Comment by fredl2020** [comment]
It shows the history of a camipro card, useful for 1234/psdn students assistants to troubleshoot some things (2fa, mfa, physical access, ect.)
you can check mine for example.
I don't know where the information is findable. We need to ask camipro team 👍

**Comment by Azecko** [comment]
Hello @ngie-mp, do you have any information about that issue ? What is `cmpcardhist` ?
Thanks :)
