### ISSUE TITLE
Add matricule SAP in Atari

### ISSUE THREAD

**Issue by nmeystre** [epfl-si/ATARI#96]
### Ajouter matricule SAP, GID, UID, Home, Shell

Bonjour,
Avec Gianni, on fait un toilettage people et je voudrais supprimer qq données administratives des pages people, dont le matricule SAP, qui aurait toute sa place sur ATARI.
Qu'en pensez-vous?
Facile ?
Cordialement
natalie
------------------------
Chère Madame Meystre,
Après consultation avec Andrea et des AEs expérimentés, la seule information qui nous intéresse et que nous pouvons trouver uniquement via people.epfl.ch est le matricule SAP. Nous l'utilisons principalement pour transmettre des tickets à SI_SESAME.
Il serait intéressant d'afficher le matricule SAP des utilisateurs dans atari.epfl.ch pour ne plus avoir à se rendre dans people. A part pour les tickets people, c'est la seule information qui nous force à aller sur people.
SCIPER, username : nous avons déjà dans ServiceNow.
Nous n'utilisons pas le reste.
Merci,
Julien D
------------------------------
Salut,
Nous avons besoin du matricule pour le support SAP mais si les AE le trouvent ailleurs (par exemple l’ajouter dans le formulaire Incident) c’est mieux.
Merci, Maude
-----------------------
 Salut Nathalie,
Ces informations sont utile pour les supports informatique, notamment les facultés (GID, UID, Home, Shell, username). Pour le matricule SAP c’est le support Sesame / Note de frais.
On a un outil qui a été fait à destination du support 1234 ([atari.epfl.ch](http://atari.epfl.ch/)) qui est plus adapté pour ce genre de cas. 
Personnellement je pense qu’il faudrait restreindre les infos type « informatiques » hors de people et les garder dans des outils dédiés comme ATARI. People devrait rester un annuaire public / CV pour se vanter :)
 A+
Quentin
-------------------------

Bonjour,
Les ID Unix (UID:GID) sont utilisées pour l'ownership et les permissions des fichiers/répertoires.
S'ils disparaissent des pages people, est-il possible de les retrouver autrement qu'avec une requête LDAP?
(ils ne figurent pas dans accred).
Bonne journée et meilleures salutations
Léonard Gross
---------------

**Comment by ponsfrilus** [comment]
c.f. [INC0644915](https://go.epfl.ch/INC0644915)

**Comment by Azecko** [comment]
Re-opened because missing the `SAP` registration number.
GID, UID, Home & Shell has been added.
